#coding=utf-8

class rename_list_utils(object):

    def rename_current_finance_utils(self,pds):
        pds.rename(columns={'col1':'EPS',
                            'col2':'deductEPS',
                            'col3':'undistributedProfitPerShare',
                            'col4':'netAssetsPerShare',
                            'col5':'capitalReservePerShare',
                            'col6':'ROE',
                            'col7':'operatingCashFlowPerShare',
                            'col8':'moneyFunds',
                            'col9':'tradingFinancialAssets',
                            'col10':'billsReceivables',
                            'col11':'accountsReceivables',
                            'col12':'prepayments',
                            'col13':'otherReceivables',
                            'col14':'interCompanyReceivables',
                            'col15':'interestReceivables',
                            'col16':'dividendsReceivables',
                            'col17':'inventory',
                            'col18':'expendableBiologicalAssets',
                            'col19':'noncurrentAssetsDueWithinOneYear',
                            'col20':'otherLiquidAssets',
                            'col21':'totalLiquidAssets',
                            'col22':'availableForSaleSecurities',
                            'col23':'heldToMaturityInvestments',
                            'col24':'longTermReceivables',
                            'col25':'longTermEquityInvestment',
                            'col26':'investmentRealEstate',
                            'col27':'fixedAssets',
                            'col28':'constructionInProgress',
                            'col29':'engineerMaterial',
                            'col30':'fixedAssetsCleanUp',
                            'col31':'productiveBiologicalAssets',
                            'col32':'oilAndGasAssets',
                            'col33':'intangibleAssets',
                            'col34':'developmentExpenditure',
                            'col35':'goodwill',
                            'col36':'longTermDeferredExpenses',
                            'col37':'deferredIncomeTaxAssets',
                            'col38':'otherNonCurrentAssets',
                            'col39':'totalNonCurrentAssets',
                            'col40':'totalAssets',
                            'col41':'shortTermLoan',
                            'col42':'tradingFinancialLiabilities',
                            'col43':'billsPayable',
                            'col44':'accountsPayable',
                            'col45':'advancedReceivable',
                            'col46':'employeesPayable',
                            'col47':'taxPayable',
                            'col48':'interestPayable',
                            'col49':'dividendPayable',
                            'col50':'otherPayable',
                            'col51':'interCompanyPayable',
                            'col52':'noncurrentLiabilitiesDueWithinOneYear',
                            'col53':'otherCurrentLiabilities',
                            'col54':'totalCurrentLiabilities',
                            'col55':'longTermLoans',
                            'col56':'bondsPayable',
                            'col57':'longTermPayable',
                            'col58':'specialPayable',
                            'col59':'estimatedLiabilities',
                            'col60':'defferredIncomeTaxLiabilities',
                            'col61': 'otherNonCurrentLiabilities',
                            'col62': 'totalNonCurrentLiabilities',
                            'col63': 'totalLiabilities',
                            'col64': 'totalShare',
                            'col65': 'capitalReserve',
                            'col66': 'surplusReserve',
                            'col67': 'treasuryStock',
                            'col68': 'undistributedProfits',
                            'col69': 'minorityEquity',
                            'col70': 'foreignCurrencyReportTranslationSpread',
                            'col71': 'abnormalBusinessProjectEarningsAdjustment',
                            'col72': 'totalOwnersEquity',
                            'col73': 'totalLiabilitiesAndOwnersEquity',
                            'col74': 'operatingRevenue',
                            'col75': 'operatingCosts',
                            'col76': 'taxAndSurcharges',
                            'col77': 'salesCosts',
                            'col78': 'managementCosts',
                            'col79': 'explorationCosts',
                            'col80': 'financialCosts',
                            'col81': 'assestsDevaluation',
                            'col82': 'profitAndLossFromFairValueChanges',
                            'col83': 'investmentIncome',
                            'col84': 'investmentIncomeFromAffiliatedBusinessAndCooperativeEnterprise',
                            'col85': 'otherSubjectsAffectingOperatingProfit',
                            'col86': 'operatingProfit',
                            'col87': 'subsidyIncome',
                            'col88': 'nonOperatingIncome',
                            'col89': 'nonOperatingExpenses',
                            'col90': 'netLossFromDisposalOfNonCurrentAssets',
                            'col91': 'otherSubjectsAffectTotalProfit',
                            'col92': 'totalProfit',
                            'col93': 'incomeTax',
                            'col94': 'otherSubjectsAffectNetProfit',
                            'col95': 'netProfit',
                            'col96': 'netProfitsBelongToParentCompanyOwner',
                            'col97': 'minorityProfitAndLoss',
                            'col98': 'cashFromGoodsSalesorOrRenderingOfServices',
                            'col99': 'refundOfTaxAndFeeReceived',
                            'col100': 'otherCashRelatedBusinessActivitiesReceived',
                            'col101': 'cashInflowsFromOperatingActivities',
                            'col102': 'buyingGoodsReceivingCashPaidForLabor',
                            'col103': 'paymentToEmployeesAndCashPaidForEmployees',
                            'col104': 'paymentsOfVariousTaxes',
                            'col105': 'paymentOfOtherCashRelatedToBusinessActivities',
                            'col106': 'cashOutflowsFromOperatingActivities',
                            'col107': 'netCashFlowsFromOperatingActivities',
                            'col108': 'cashReceivedFromInvestmentReceived',
                            'col109': 'cashReceivedFromInvestmentIncome',
                            'col110': 'disposalOfNetCashForRecoveryOfFixedAssetsIntangibleAssetsAndOtherLongTermAssets',
                            'col111': 'disposalOfNetCashReceivedFromSubsidiariesAndOtherBusinessUnits',
                            'col112': 'otherCashReceivedRelatingToInvestingActivities',
                            'col113': 'cashinFlowsFromInvestmentActivities',
                            'col114': 'cashForThePurchaseConstructionPaymentOfFixedAssetsIntangibleAssetsAndOtherLongTermAssets',
                            'col115': 'cashInvestment',
                            'col116': 'acquisitionOfNetCashPaidBySubsidiariesAndOtherBusinessUnits',
                            'col117': 'otherCashPaidRelatingToInvestingActivities',
                            'col118': 'cashOutflowsFromInvestmentActivities',
                            'col119': 'netCashFlowsFromInvestingActivities',
                            'col120': 'cashReceivedFromInvestors',
                            'col121': 'cashFromBorrowings',
                            'col122': 'otherCashReceivedRelatingToFinancingActivities',
                            'col123': 'cashInflowsFromFinancingActivities',
                            'col124': 'cashPaymentsOfAmountBorrowed',
                            'col125': 'cashPaymentsForDistrbutionOfDividendsOrProfits',
                            'col126': 'otherCashPaymentRelatingToFinancingActivities',
                            'col127': 'cashOutflowsFromFinancingActivities',
                            'col128': 'netCashFlowsFromFinancingActivities',
                            'col129': 'effectOfForeignExchangRateChangesOnCash',
                            'col130': 'effectOfOtherReasonOnCash',
                            'col131': 'netIncreaseInCashAndCashEquivalents',
                            'col132': 'initialCashAndCashEquivalentsBalance',
                            'col133': 'theFinalCashAndCashEquivalentsBalance',
                            'col134': 'netProfitFromOperatingActivities',
                            'col135': 'provisionForAssetsLosses',
                            'col136': 'depreciationForFixedAssets',
                            'col137': 'amortizationOfIntangibleAssets',
                            'col138': 'amortizationOfLong-termDeferredExpenses',
                            'col139': 'lossOfDisposingFixedAssetsIntangibleAssetsAndOtherLong-termAssets',
                            'col140': 'scrapLossOfFixedAssets',
                            'col141': 'lossFromFairValueChange',
                            'col142': 'financialExpenses',
                            'col143': 'investmentLosses',
                            'col144': 'decreaseOfDeferredTaxAssets',
                            'col145': 'increaseOfDeferredTaxLiabilities',
                            'col146': 'decreaseOfInventory',
                            'col147': 'decreaseOfOperationReceivables',
                            'col148': 'increaseOfOperationPayables',
                            'col149': 'others',
                            'col150': 'netCashFromOperatingActivities2',
                            'col151': 'debtConvertedToCSapital',
                            'col152': 'convertibleBondMaturityWithinOneYear',
                            'col153': 'leaseholdImprovements',
                            'col154': 'cashEndingBal',
                            'col155': 'cashBeginingBal',
                            'col156': 'cashEquivalentsEndingBal',
                            'col157': 'cashEquivalentsBeginningBal',
                            'col158': 'netIncreaseOfCashAndCashEquivalents',

                            #--
                            'col159': 'currentRatio',
                            'col160': 'acidTestRatio',
                            'col161': 'cashRatio',
                            'col162': 'interestCoverageRatio',
                            'col163': 'noncurrentLiabilitiesRatio',
                            'col164': 'currentLiabilitiesRatio',
                            'col165': 'cashDebtRatio',
                            'col166': 'debtToTangibleAssetsRatio',
                            'col167': 'equityMultiplier',
                            'col168': 'equityDebtRatio',
                            'col169': 'tangibleAssetDebtRatio',
                            'col170': 'netCashFlowsFromOperatingActivitiesDebtRatio',
                            'col171': 'ebitda-liabilities',

                            #--
                            'col172': 'turnoverRatioOfReceivable',
                            'col173': 'turnoverRatioOfInventory',
                            'col174': 'turnoverRatioOfOperatingAssets',
                            'col175': 'turnoverRatioOfTotalAssets',
                            'col176': 'turnoverRatioOfFixedAssets',
                            'col177': 'daysSalesOutstanding',
                            'col178': 'daysSalesOfInventory',
                            'col179': 'turnoverRatioOfCurrentAssets',
                            'col180': 'daysSalesofCurrentAssets',
                            'col181': 'daysSalesofTotalAssets',
                            'col182': 'equityTurnover',

                            #--
                            'col183': 'operatingIncomeGrowth',
                            'col184': 'netProfitGrowthRate',
                            'col185': 'netAssetsGrowthRate',
                            'col186': 'fixedAssetsGrowthRate',
                            'col187': 'totalAssetsGrowthRate',
                            'col188': 'investmentIncomeGrowthRate',
                            'col189': 'operatingProfitGrowthRate',
                            'col190': 'None1',
                            'col191': 'None2',
                            'col192': 'None3',

                            #--
                            'col193': 'rateOfReturnOnCost',
                            'col194': 'rateOfReturnOnOperatingProfit',
                            'col195': 'rateOfReturnOnBusinessTax',
                            'col196': 'rateOfReturnOnOperatingCost',
                            'col197': 'rateOfReturnOnCommonStockholdersEquity',
                            'col198': 'rateOfReturnOnInvestmentIncome',
                            'col199': 'rateOfReturnOnNetSalesProfit',
                            'col200': 'rateOfReturnOnTotalAssets',
                            'col201': 'netProfitMargin',
                            'col202': 'rateOfReturnOnGrossProfitFromSales',
                            'col203': 'threeFeeProportion',
                            'col204': 'ratioOfChargingExpense',
                            'col205': 'ratioOfFinancialExpense',
                            'col206': 'netProfitAfterExtraordinaryGainsAndLosses',
                            'col207': 'EBIT',
                            'col208': 'EBITDA',
                            'col209': 'ebitda-grossRevenueRate',

                            #--
                            'col210': 'assetsLiabilitiesRatio',
                            'col211': 'currentAssetsRatio',
                            'col212': 'monetaryFundRatio',
                            'col213': 'inventoryRatio',
                            'col214': 'fixedAssetsRatio',
                            'col215': 'liabilitiesStructureRatio',
                            'col216': 'shareholdersOwnershipOfAParentCompany-totalCapital',
                            'col217': 'shareholdersInterest-interestRateDebtRatio',
                            'col218': 'tangibleAssets-netDebtRatio',

                            #--
                            'col219': 'operatingCashFlowPerShare',
                            'col220': 'cashOfOperatingIncome',
                            'col221': 'netOperatingCashFlow-netOperationProfit',
                            'col222': 'cashFromGoodsSales-operatingRevenue',
                            'col223': 'netOperatingCashFlow-operatingRevenue',
                            'col224': 'capitalExpenditure-depreciationAndAmortization',
                            'col225': 'netCashFlowPerShare',
                            'col226': 'operatingCashFlow-shortTermDebtRatio',
                            'col227': 'operatingCashFlow-longTermDebtRatio',
                            'col228': 'cashFlowRateAndNetProfitRatioOfOperatingActivities',
                            'col229': 'cashRecoveryForAllAssets',

                            #--单季度财务指标
                            'col230': 'operatingRevenueSingle',
                            'col231': 'operatingProfitSingle',
                            'col232': 'netProfitBelongingToTheOwnerOfTheParentCompanySingle',
                            'col233': 'netProfitAfterExtraordinaryGainsAndLossesSingle',
                            'col234': 'netCashFlowsFromOperatingActivitiesSingle',
                            'col235': 'netCashFlowsFromInvestingActivitiesSingle',
                            'col236': 'netCashFlowsFromFinancingActivitiesSingle',
                            'col237': 'netIncreaseInCashAndCashEquivalentsSingle',

                            #--股本股东
                            'col238': 'totalCapital',
                            'col239': 'listedAShares',
                            'col240': 'listedBShares',
                            'col241': 'listedHShares',
                            'col242': 'numberOfShareholders',
                            'col243': 'theNumberOfFirstMajorityShareholder',
                            'col244': 'totalNumberOfTopTenCirculationShareholders',
                            'col245': 'totalNumberOfTopTenMajorShareholders'},inplace=True)
        return pds